name: Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: testing
      - name: Install dependencies
        run: |
          conda install -c conda-forge python-graphblas scipy pandas \
            pytest-cov pytest-randomly black flake8-comprehensions flake8-bugbear hypothesis
            # matplotlib lxml pygraphviz pydot sympy  # Extra networkx deps we don't need yet
          pip install git+https://github.com/networkx/networkx.git@main --no-deps
          pip install -e . --no-deps
      - name: Style checks
        run: |
          flake8
          black . --check --diff
      - name: PyTest
        run: |
          coverage run --branch -m pytest -v
          coverage xml
      - name: Coverage
        uses: codecov/codecov-action@v2
